product_name= input("Enter a product name")
price = int(input("Enter the price"))
quantity=int(input("Enter a quantity"))
total_cost= (price*quantity)
print("product name", product_name)
print("price is", str(price))
print("quanitiy is", str(quantity))
print("Total cost is", total_cost)

print(type(total_cost))